apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: default
data:
  PRODUCTION_DB_NAME: "dummy_db"
  PRODUCTION_DB_HOST: "postgres"
  PRODUCTION_DB_USERNAME: "dummy_user"
  PRODUCTION_DB_PASSWORD: "secretpassword"
  PRODUCTION_DB_PORT: "5432"
  SECRET_KEY_BASE: asecuretokenwouldnormallygohere
  LISTEN_ON: 0.0.0.0:8000
  WORKER_PROCESSES: "1"
  JOB_WORKER_URL: redis://redis:6379/0 