apiVersion: v1
kind: Service
metadata:
  name: devops
  labels:
    name: devops-service
spec:
  selector:
    app: devops
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http